apiVersion: v1
kind: Service
metadata:
  name: cart-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: cart
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: cart
  sessionAffinity: None
